server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://43.138.55.241:3306/app_schema?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456789
      max-active: 30
      min-idle: 5
      validation-query: SELECT 1 FROM DUAL
      max-wait: 100000000
      min-evictable-idle-time-millis: 30000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j2
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow: 0.0.0.0
        reset-enable: false
        login-username: admin
        login-password: admin

  redis:
    # redis种第几个库
    database: 0
    # ip
    host: 127.0.0.1
    # 端口
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 3000
    jedis:
      pool:
        # 最大连接数
        max-active: 200
        # 连接池出借连接的最长期限
        max-wait: -1
        # 最多维持空闲连接
        max-idle: 10
        # 最少维持空闲连接
        min-idle: 10

  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 100MB
      # 设置单次请求文件的总大小
      max-request-size: 100MB

#配置全局变量 mybatis配置
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#FTP配置
FTP:
  ADDRESS: 43.138.55.241
  PORT: 22
  USERNAME: root
  PASSWORD: WeiXinDaKa/*-+892951659
  BASE-PATH: /home/image
  URL: ftp:43.138.55.241/home/image


